#cloud-config
write_files:
  - path: /tmp/test
    content: |
        YAML is wonderful
coreos:
  units:
    - name: etcd.service
      command: start

    - name: fleet.service
      command: start
  etcd:
    discovery: https://discovery.etcd.io/d259912ba681a5ce1731e55243f13fa3
    addr: "$public_ipv4:4001"
    peer-addr: "$private_ipv4:7001"

  fleet:
    public-ip: "$private_ipv4"
    metadata: region=pezlab,public_ip=$public_ipv4
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC64JbzrJ3rhR+OBIvha3T4kRWl12GY8lGxRxDD8+naQdTpiRpup/bkYywupDk/tvy4rGZ4Y4r6C/g4AZM0s9TRdN/0ZEuk7u9DgCuK7/ouxbtK0wTSrBFIYc5m1RifJVrdpRZmHOJX4tgU3fJ7mUq5hUIbGSRTxF3U89PN4Z8ERMniPyEHuildFo9UXq7PP69Po7b7SdVjUkULnGCy+Zp936GOG8avNdGnUxu6SSo3Ru0xGU+2ftsb9rN/0p4a62p8FX/num9zuAlTymVSw1XzmdnzqZHbdd9Q/lkGz48D7fl+pWAYsiU2AbmofeH+jl+MHx1TsEcLW+kK/ReDWzECM1DecyG0baWaZnP92yWi/KapXb9mnjC1Pswv2RYilg8VyqepJkvlrcHGgvov+Dux0JpcP2hDRP3mmZu6+oOAs4VsjXJz7DouENCW1txrGFic37dLRkKhvVmsMhkF8jArNHXVMLdGnMo3OsgGdxwnd6XLRm8Uhmh9VZcCLCYtLxrDihlflV45o/tRauf72XF0WaUU/IXXPcQMTN7uTsElRGmLRi5NDV5nYtgS2Tk3YwRgL7u6qTf0pOlN4b50EZ5PiyLmOQBmiCTT64ibmrrv7qgEbvHR3aUjpg89iUsgxI+I/EWMjY677BdLhVEQQeZY+MUK9IKjlMqMjtKkDAbKrQ== pezhore@gmail.com
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTfb0pGmJPd8mp24ChfdPutuOyIuW3TSip2SZdZOw74kV71y1w8pVk7w/fTKSNJzN7CZH8K7ZTDtWZ2m/Det036C2JR4WdSbXyKUWz4nFh5ojQ+oW6QfZy8wDnqxfWc/V7dth2iYZTpFkOuHx1+1vUrOVrmUyaHhae+qGoH0y/W5xpbZ/HyfcITu+Uui4leBrGY25zb0bccKuN/GnHOrDwBtBp4m544GEgRe1ujuFO244gtOH7FCUge8M/8MHxcg4iOZbWE4szEOZMMqsxpnDUYeYc6700TderUQ7ihRreYbBNNj77SmafybArQ68IUOytO81P9C6pTyoN4kjJ0Xx98pg1HtDxy6lscemckBlZ06qP+iS++XcRNaAd77WbEanZLdHuXmgTvGinGkpjHMrDvxsFMXS477gqNLb7CeVe4YRNjD1kdDRzE6dUJM6ajs4JbypsB5BoNVbslXwh3SjTf113OcpHD8fva/PxCNjE7STV9ji2EPrkWxq95N9+5Rj7hz1cCHgX8+w1m5Y+W3yao1bB87lC6CgLvLK+uDlJ3X8A9ZXQCQ5ndHO+WvKx4JoLEbRy7aMwr7hiArzoB4Fb0nfPWpAovcMFFujNwUuTXRNYUIPZ3t2kT1ta7UqqPSMumwOQOK5Pc14VUCJM0YUq9Q/0HWMZQFPSEPXcL/gsdQ== ahawkins.mail@gmail.com
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDoC1KWDNO1lzFKPj1PQjc7bbH0zPSJYVEZ6DmcqWMTSyAxATDHYTj3qmW3Vcy48Dof7H5tgZCEsIPYqS+THnxfkQYmE5djnFHUUPPe1UjG2X/JwjF7Y0i+gGPvsU3RLZrc/xAUF6J0moSiBzjzNN2/kC6Hj0Jj9mKCEpyZwc/rjonWadnYHY3eSeqPxKL+6IiEN1qZCORLJl0i7N+tWo9ruYpBkY82WczAzXWbdRw/ti2kSGn3vnnIj9TC2Z0jUsIvckUS4a7Cw/2uyxQw9M54dbD4W7OtN4jxhqh3tIJtdhskECTTqTIanGk9s0uAFAyRy2qTi/CFTg3qjPrWr1AWjqD8PDadG/fxoljTGe1FESI8Yw1Ky9JOEM8PzlKaaDte8/QdoucoKEA22YlehtVXAGA3iAYEWI/hx4AbERMs51sQsZRimg39SR9Ha+pg0bqTQYUyrBmn4NMMI9XT/suZi/xOgVf0OpjKl4c30tcKwiysTUA8xng93t7DLVl5OgydM02uiYyGmK3sm0zyY3laMxieycuqcGzUDD/dr7D7ZfdDtQRi7fv43P7G0Qp1e/H343ALpcFyDbucpQeaeTEB49LVHUB+8ZG7m5BYYbSSBWDMYIL9ykj/9TXaxg3dWPLv0rAvJ/EpOE+ivfKzE0+WU82L10YYbVBYltk1nmft+Q== pezhore@gmail.com
